import { StyleSheet } from "react-native";

const mapStyles = StyleSheet.create({
  container: {
    flex: 1,
  },
  header: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    backgroundColor: "#3300CC",
    paddingHorizontal: 16,
    paddingVertical: 20,
    borderBottomStartRadius: 10,
    borderBottomEndRadius: 10,
  },
  headerTitle: {
    color: "#fff",
    fontSize: 22,
    fontWeight: "bold",
    marginRight: "auto",
  },
  // menuButton: {
  //   marginRight: 20,
  // },
  iconContainer: {
    flexDirection: "row",
    marginLeft: "auto",
  },
  icon: {
    marginRight: 10,
  },
  cardContainer: {
    backgroundColor: "#CCCCFF",
    overflow: "hidden",
    marginHorizontal: 16,
    marginVertical: 8,
    padding: 16,
    borderRadius: 8,
  },
  cardDate: {
    fontSize: 10,
    marginBottom: 8,
    marginTop: 8,
  },
  cardText: {
    fontSize: 14,
    color: "#666",
    marginBottom: 8,
  },
  textContainer: {
    padding: 10,
    backgroundColor: "#fff",
    borderBottomLeftRadius: 10,
    borderBottomRightRadius: 10,
  },
  addressContainer: {
    backgroundColor: "#fff",
    marginHorizontal: 16,
    marginVertical: 8,
    padding: 16,
    borderRadius: 8,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  addressSection: {
    backgroundColor: "#fff",
    marginHorizontal: 16,
    marginVertical: 8,
    borderRadius: 8,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
    padding: 16,
  },
  addressItem: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 8,
    paddingBottom: 8,
    borderBottomWidth: 1,
    borderBottomColor: "#8f8f8f",
  },
  addressIcon: {
    marginRight: 8,
    color: "#8f8f8f",
  },
  addressTextContainer: {
    flex: 1,
  },
  addressName: {
    fontWeight: "bold",
    fontSize: 16,
    marginBottom: 4,
  },
  addressInfo: {
    color: "#8f8f8f",
    fontSize: 14,
  },
  mapContainer: {
    backgroundColor: "#fff",
    height: 200,
    marginHorizontal: 16,
    marginVertical: 8,
    border: "solid",
    borderWidth: 8,
    borderRadius: 8,
    borderColor: "#fff",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
    overflow: "hidden",
    zIndex: -1,
  },
  map: {
    flex: 1,
    width: "100%",
  },
  zoomControl: {
    position: "absolute",
    bottom: 16,
    right: 16,
    flexDirection: "column",
    backgroundColor: "#fff",
    borderRadius: 4,
    overflow: "hidden",
  },
  zoomButton: {
    width: 40,
    height: 40,
    justifyContent: "center",
    alignItems: "center",
    borderBottomWidth: 1,
    borderBottomColor: "#ccc",
  },

  infoContainer: {
    backgroundColor: "#fff",
    marginHorizontal: 16,
    marginVertical: 8,
    paddingVertical: 16,
    paddingHorizontal: 8,
    borderRadius: 8,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  infoBackground: {
    backgroundColor: "#F2F2F2",
    height: "100%",
    width: "100%",
    position: "absolute",
    top: 0,
    left: 0,
    zIndex: -1,
  },
  infoItem: {
    flexDirection: "row",
    alignItems: "center",
    marginRight: 16,
  },
  infoIcon: {
    marginRight: 8,
    color: "#8f8f8f",
  },
  infoText: {
    fontSize: 16,
    fontWeight: "bold",
    color: "#8f8f8f",
  },
});

export default mapStyles;
